name: Nomad
description: "A Travel Flutter App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true
  assets:
    - assets/hitgano21.png
    - assets/ateneo.jpeg
    - assets/josh.jpg
    - assets/vive.jpg
    - assets/lego.jpg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/travel.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/travel.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/travel.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/travel.png"
